name: Court call scrape

on:
  workflow_dispatch:
  schedule:
     - cron: '15 10 * * *'

jobs:
  scrape:
    name: Scrape court calls
    uses: ./.github/workflows/scrape.yml
    with:
      command: make -f Makefile.courtcalls all
    secrets: inherit

  deploy:
    name: Deploy to Heroku
    needs: scrape
    uses: ./.github/workflows/heroku_deploy.yml
    with:
      heroku_app_name: ""
    secrets: inherit
