name: Nightly case scrape

on:
  workflow_dispatch:
    inputs:
      command:
        required: true
        type: string
        default: make get_new_records

  # schedule:
  #    - cron: '15 4 * * *'

jobs:
  manual_scrape:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Scrape new cases
    uses: ./.github/workflows/scrape.yml
    with:
      command: ${{ github.event.inputs.command }}
    secrets: inherit

  scheduled_scrape:
    if: ${{ github.event_name == 'schedule' }}
    name: Scrape new cases
    uses: ./.github/workflows/scrape.yml
    with:
      command: make get_new_records
    secrets: inherit

  deploy:
    name: Deploy to Heroku
    if: ${{ always() && (needs.scheduled_scrape.result == 'success' || needs.scheduled_scrape.result == 'success') }}}}
    needs: [manual_scrape, scheduled_scrape]
    uses: ./.github/workflows/heroku_deploy.yml
    with:
      heroku_app_name: ""
    secrets: inherit
