name: Nightly case scrape

on:
  workflow_dispatch:
  schedule:
     - cron: '15 4 * * *'

jobs:
  scrape:
    name: Scrape new cases
    uses: ./.github/workflows/scrape.yml
    with:
      command: make get_new_records
      case_db_pw: ${{ secrets.CASE_DB_PW }}

  deploy:
    name: Deploy to Heroku
    needs: scrape
    uses: ./.github/workflows/deploy-to-heroku.yml
    with:
      heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      heroku_email: ${{ secrets.HEROKU_EMAIL }}
      heroku_app_name: ""
      case_db_pw: ${{ secrets.CASE_DB_PW }}
