name: Nightly case scrape

on:
  workflow_dispatch:
  schedule:
     - cron: '15 4 * * *'

jobs:
  scrape:
    name: Scrape new cases
    uses: ./.github/workflows/scrape.yml
    with:
      command: make get_new_records
    secrets: inherit

  deploy:
    name: Deploy to Heroku
    needs: scrape
    uses: ./.github/workflows/heroku_deploy.yml
    with:
      heroku_app_name: ""
    secrets: inherit
