name: Nightly case scrape

on:
  workflow_dispatch:
  schedule:
     - cron: '15 4 * * *'
  inputs:
    command:
      required: true
      type: string
      default: make get_new_records

jobs:
  scrape:
    name: Scrape new cases
    uses: ./.github/workflows/scrape.yml
    with:
      command: ${{ github.event.inputs.command }}
    secrets: inherit

  deploy:
    name: Deploy to Heroku
    needs: scrape
    uses: ./.github/workflows/heroku_deploy.yml
    with:
      heroku_app_name: ""
    secrets: inherit
