name: Publish Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker images to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Packages
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:main
