name: Rescrape cases

on:
  workflow_dispatch:
  schedule:
     - cron: '0 21 * * *'

jobs:
  scrape:
    name: Rescrape cases
    uses: ./.github/workflows/scrape.yml
    with:
      command: make -f Makefile.update update_db
      case_db_pw: ${{ secrets.CASE_DB_PW }}

  deploy:
    name: Deploy to Heroku
    needs: scrape
    uses: ./.github/workflows/deploy-to-heroku.yml
    with:
      heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      heroku_email: ${{ secrets.HEROKU_EMAIL }}
      heroku_app_name: ""
      case_db_pw: ${{ secrets.CASE_DB_PW }}
