name: Rescrape cases

on:
  workflow_dispatch:
  schedule:
     - cron: '0 21 * * *'

jobs:
  scrape:
    name: Rescrape cases
    uses: ./.github/workflows/scrape.yml
    with:
      command: make -f Makefile.update update_db
    secrets: inherit

  deploy:
    name: Deploy to Heroku
    needs: scrape
    uses: ./.github/workflows/heroku_deploy.yml
    secrets: inherit
